apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- http-route.yaml
images:
- name: ghcr.io/gitops-ci-cd/red
  newTag: fbe765a135534b1dedb9dcd53488c599440ac82d
